AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/UnneededSplatExpansion:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SingleLineBlockParams:
  Enabled: false

Style/SpaceBeforeSemicolon:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false
